<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;IDE0161;IDE0290;IDE0078</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;IDE0161;IDE0290;IDE0078</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" Version="17.1.0" />
  </ItemGroup>

</Project>
